create table students (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matnr varchar(80) not null,
    firstname varchar(80) null,
    lastname varchar(80) null,
    email varchar(80) null
);