package at.ac.tuwien.ifs.bpse.dao.interfaces;

import java.util.List;

import at.ac.tuwien.ifs.bpse.domain.Course;
import at.ac.tuwien.ifs.bpse.domain.Exam;

/**
 * The DAO abstracts and encapsulates all access to the data source corresponding to the Course
 * business object
 * @author The SE-Team
 * @version 1.0
 */
public interface ICourseDAO {
    /**
     * Retrieves one single Course from the DB.
     * @param id unique database ID of Course
     * @return Course object holding the data or null if no Course with the matching id is found
     */
    public Course getCourse(int id);

    /**
     * Save one single Course to the Database.
     * @param Course object holding the data of one Course
     * @return new Course object containing a unique id generated by database
     */
    public Course saveCourse(Course Course);

    /**
     * Updates an existing Course in the database.
     * @param Course object holding the data of one Course
     * @return updated Course
     */
    public Course updateCourse(Course Course);

    /**
     * Deletes an existing Course from the database.
     * @param Course object
     * @return true if procedure was successfully, otherwise false
     */
    public boolean deleteCourse(Course course);
    
    
    /**
     * Search course by title
     * @param title of the course
     * @return list of matched courses
     */
    public List<Course> getCourseByTitle(String title);
    
    /**
     * Retrieve a list of exams registered for the course
     * @param course
     * @return list of course
     */
    public List<Exam> getExamsOfCourse(Course course);
    
}
