package at.ac.tuwien.ifs.bpse.dao.interfaces;

import java.util.List;

import at.ac.tuwien.ifs.bpse.domain.Exam;
import at.ac.tuwien.ifs.bpse.domain.StudentExam;

/**
 * The DAO abstracts and encapsulates all access to the data source corresponding to the Exam
 * business object
 * @author The SE-Team
 * @version 1.0
 */
public interface IExamDAO {
    /**
     * Retrieves one single Exam from the DB.
     * @param id unique database ID of Exam
     * @return Exam object holding the data or null if no exam with the matching id is found
     */
    public Exam getExam(int id);

    /**
     * Save one single Exam to the Database.
     * @param exam object holding the data of one exam
     * @return new exam object containing a unique id generated by database
     */
    public Exam saveExam(Exam exam);

    /**
     * Updates an existing exam in the database.
     * @param exam object holding the data of one exam
     * @return updated exam
     */
    public Exam updateExam(Exam exam);
    
    /**
     * Retrieve a list af all exams
     * @return list of exams
     */
    public List<Exam> getExams();
    
    /**
     * Save an exam for a student assigned for a course
     */
    public StudentExam saveStudentExam(StudentExam studentExam);
}
