create table users (
      username varchar_ignorecase(50) not null primary key,
      password varchar_ignorecase(50) not null,
      enabled boolean not null
);
create table authorities (
      username varchar_ignorecase(50) not null,
      authority varchar_ignorecase(50) not null,
      constraint fk_authorities_users foreign key(username) references users(username));
      create unique index ix_auth_username on authorities (username,authority);
      
CREATE table student (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matnr char(7) NOT NULL,
    firstname varchar(20) NOT NULL,
    lastname varchar(40) NOT NULL,
    email varchar(50) NOT NULL FOREIGN KEY REFERENCES users(username)
);
CREATE table tutor (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matnr char(7) NOT NULL,
    firstname varchar(20) NOT NULL,
    lastname varchar(40) NOT NULL,
    email varchar(50) NOT NULL FOREIGN KEY REFERENCES users(username)
);
CREATE table course (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(80) NOT NULL,
    ects float NOT NULL
);
CREATE table professor (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	officenr varchar(80) NOT NULL,
	firstname varchar(20) NOT NULL,
    lastname varchar(40) NOT NULL,
    email varchar(50) NOT NULL FOREIGN KEY REFERENCES users(username)
);
CREATE table course_professor (
	courseId integer FOREIGN KEY REFERENCES course(id) ON DELETE CASCADE,
	professorId integer FOREIGN KEY REFERENCES professor(id) ON DELETE CASCADE
);
CREATE table exam (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	exdate timestamp NOT NULL,
	location varchar(20) NOT NULL,
    courseId integer FOREIGN KEY REFERENCES course(id) ON DELETE CASCADE
);
CREATE table student_exam (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	studentId integer FOREIGN KEY REFERENCES student(id) ON DELETE CASCADE,
	tutorId integer FOREIGN KEY REFERENCES tutor(id) ON DELETE CASCADE,
	examId integer FOREIGN KEY REFERENCES exam(id) ON DELETE CASCADE
);